site_name: Seongcheol Jeon - blog
site_url: https://seongcheoljeon.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/seongcheoljeon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/saelly55
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seongcheol-jeon-368a17205

copyright:
  &copy; 2023 <a href="https://github.com/seongcheoljeon" target="_blank" rel="noopener">Seongcheol Jeon</a>