require 'rouge'

# Use a known sample of all CSS classes Rouge can emit
tokens = [
  Rouge::Token::Tokens::Comment,
  Rouge::Token::Tokens::Comment::Doc,
  Rouge::Token::Tokens::Comment::Multiline,
  Rouge::Token::Tokens::Comment::Preproc,
  Rouge::Token::Tokens::Comment::PreprocFile,
  Rouge::Token::Tokens::Comment::Single,
  Rouge::Token::Tokens::Comment::Special,
  Rouge::Token::Tokens::Comment::Hashbang,
  Rouge::Token::Tokens::Error,
  Rouge::Token::Tokens::Escape,
  Rouge::Token::Tokens::Generic,
  Rouge::Token::Tokens::Generic::Deleted,
  Rouge::Token::Tokens::Generic::Emph,
  Rouge::Token::Tokens::Generic::EmphStrong,
  Rouge::Token::Tokens::Generic::Error,
  Rouge::Token::Tokens::Generic::Heading,
  Rouge::Token::Tokens::Generic::Inserted,
  Rouge::Token::Tokens::Generic::Lineno,
  Rouge::Token::Tokens::Generic::Output,
  Rouge::Token::Tokens::Generic::Prompt,
  Rouge::Token::Tokens::Generic::Strong,
  Rouge::Token::Tokens::Generic::Subheading,
  Rouge::Token::Tokens::Generic::Traceback,
  Rouge::Token::Tokens::Keyword,
  Rouge::Token::Tokens::Keyword::Constant,
  Rouge::Token::Tokens::Keyword::Declaration,
  Rouge::Token::Tokens::Keyword::Namespace,
  Rouge::Token::Tokens::Keyword::Pseudo,
  Rouge::Token::Tokens::Keyword::Reserved,
  Rouge::Token::Tokens::Keyword::Type,
  Rouge::Token::Tokens::Keyword::Variable,
  Rouge::Token::Tokens::Literal,
  Rouge::Token::Tokens::Literal::Date,
  Rouge::Token::Tokens::Literal::Number,
  Rouge::Token::Tokens::Literal::Number::Bin,
  Rouge::Token::Tokens::Literal::Number::Float,
  Rouge::Token::Tokens::Literal::Number::Hex,
  Rouge::Token::Tokens::Literal::Number::Integer,
  Rouge::Token::Tokens::Literal::Number::Integer::Long,
  Rouge::Token::Tokens::Literal::Number::Oct,
  Rouge::Token::Tokens::Literal::Number::Other,
  Rouge::Token::Tokens::Literal::String,
  Rouge::Token::Tokens::Literal::String::Affix,
  Rouge::Token::Tokens::Literal::String::Backtick,
  Rouge::Token::Tokens::Literal::String::Char,
  Rouge::Token::Tokens::Literal::String::Delimiter,
  Rouge::Token::Tokens::Literal::String::Doc,
  Rouge::Token::Tokens::Literal::String::Double,
  Rouge::Token::Tokens::Literal::String::Escape,
  Rouge::Token::Tokens::Literal::String::Heredoc,
  Rouge::Token::Tokens::Literal::String::Interpol,
  Rouge::Token::Tokens::Literal::String::Other,
  Rouge::Token::Tokens::Literal::String::Regex,
  Rouge::Token::Tokens::Literal::String::Single,
  Rouge::Token::Tokens::Literal::String::Symbol,
  Rouge::Token::Tokens::Name,
  Rouge::Token::Tokens::Name::Attribute,
  Rouge::Token::Tokens::Name::Builtin,
  Rouge::Token::Tokens::Name::Builtin::Pseudo,
  Rouge::Token::Tokens::Name::Class,
  Rouge::Token::Tokens::Name::Constant,
  Rouge::Token::Tokens::Name::Decorator,
  Rouge::Token::Tokens::Name::Entity,
  Rouge::Token::Tokens::Name::Exception,
  Rouge::Token::Tokens::Name::Function,
  Rouge::Token::Tokens::Name::Function::Magic,
  Rouge::Token::Tokens::Name::Label,
  Rouge::Token::Tokens::Name::Namespace,
  Rouge::Token::Tokens::Name::Other,
  Rouge::Token::Tokens::Name::Property,
  Rouge::Token::Tokens::Name::Tag,
  Rouge::Token::Tokens::Name::Variable,
  Rouge::Token::Tokens::Name::Variable::Class,
  Rouge::Token::Tokens::Name::Variable::Global,
  Rouge::Token::Tokens::Name::Variable::Instance,
  Rouge::Token::Tokens::Name::Variable::Magic,
  Rouge::Token::Tokens::Operator,
  Rouge::Token::Tokens::Operator::Word,
  Rouge::Token::Tokens::Other,
  Rouge::Token::Tokens::Punctuation,
  Rouge::Token::Tokens::Punctuation::Indicator,
  Rouge::Token::Tokens::Text,
  Rouge::Token::Tokens::Text::Whitespace,
]

fmt = Rouge::Formatters::HTML.new
results = tokens.map do |t|
  span = fmt.span(t, "x")
  cls  = span[/class="([^"]*)"/, 1]
  "#{cls.to_s.ljust(10)} => #{t}"
end

puts results.sort.uniq.join("\n")
